image: Visual Studio 2019

environment:
  # For Python versions available on Appveyor, see
  # https://www.appveyor.com/docs/windows-images-software/#python
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python37-x64"
    - PYTHON: "C:\\Python38"
    - PYTHON: "C:\\Python38-x64"
    - PYTHON: "C:\\Python39-x64"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python.exe -m pip install codecov coverage nose"
  - choco install -y swig
  - python.exe setup.py build_ext --inplace

build: off

test_script:
  - "nosetests --with-coverage --cover-branches"

on_success:
  - "codecov"
