environment:
  # For Python versions available on Appveyor, see
  # https://www.appveyor.com/docs/windows-images-software/#python
  matrix:
    - {APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017, PYTHON: "C:\\Python36-x64"}
    - {APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019, PYTHON: "C:\\Python38-x64"}
    - {APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019, PYTHON: "C:\\Python39-x64"}
    - {APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022, PYTHON: "C:\\Python313-x64"}

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python.exe -m pip install codecov coverage pytest-cov setuptools"
  - choco install -y swig
  - python.exe setup.py build_ext --inplace

build: off

test_script:
  - "py.test --cov=ihm --cov-branch -v ."

on_success:
  - "codecov"
