sudo: false
language: python
python:
  - 2.6
  - 2.7
  - 3.6
addons:
  apt:
    packages:
    - libglib2.0-dev
    - swig
cache:
  pip: true
install:
  - pip install coverage
script:
  - CFLAGS="-coverage" python setup.py build_ext --inplace -t build
  - nosetests --with-coverage --cover-branches
  - gcov -o build/src/ src/ihm_format.c
after_success:
  - bash <(curl -s https://codecov.io/bash)
