sudo: false
language: python
python:
  - 2.6
  - 2.7
  - 3.6
addons:
  apt:
    packages:
    - libglib2.0-dev
    - swig
cache:
  pip: true
install:
  - pip install coverage
script:
  - python setup.py build
  - nosetests --with-coverage --cover-branches
after_success:
  - bash <(curl -s https://codecov.io/bash)
